### ISSUE TITLE
Incompatible with VoxelMap 1.10.7

### ISSUE THREAD

**Issue by thedax** [grondag/clear-skies#2]
Both mods attempt to redirect `onGetHorizontalPlaneDot`, but due to this not being possible (presumably, since the log warns and then throws an exception), and presumably due to Clear Skies having `require = 1` set in the redirect, the game crashes upon startup.

Exception log:

```
[23:05:09] [main/WARN]: @Redirect conflict. Skipping clear-skies.client.json:MixinBackgroundRenderer->@Redirect::onGetHorizontalPlaneDot(Lnet/minecraft/class_1160;Lnet/minecraft/class_1160;)F with priority 1000, already redirected by mixin.voxelmap.json:ONMixinBackgroundRenderer->@Redirect::onDotProduct(Lnet/minecraft/class_1160;Lnet/minecraft/class_1160;)F with priority 1000
[23:05:09] [main/INFO]: [STDERR]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onGetHorizontalPlaneDot(Lnet/minecraft/class_1160;Lnet/minecraft/class_1160;)F in clear-skies.client.json:MixinBackgroundRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap clear-skies-refmap.json
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
[23:05:09] [main/INFO]: [STDERR]: 	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
[23:05:09] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
[23:05:09] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
[23:05:09] [main/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[23:05:09] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1012)
[23:05:09] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:654)
[23:05:09] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:215)
[23:05:09] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:05:09] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[23:05:09] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:05:09] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[23:05:09] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[23:05:09] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[23:05:09] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[23:05:09] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:05:09] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[23:05:09] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:05:09] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[23:05:09] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[23:05:09] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[23:05:09] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[23:05:09] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[... likely irrelevant unreported exception stuff skipped]
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onGetHorizontalPlaneDot(Lnet/minecraft/class_1160;Lnet/minecraft/class_1160;)F in clear-skies.client.json:MixinBackgroundRenderer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap clear-skies-refmap.json
```

I've noticed that Clear Skies still seems to work correctly if `require` is set to 0 on this particular redirect in MixinBackgroundRenderer.java, but I don't know enough about coding Minecraft mods to say if that's the "correct" solution or not.

System info:
Java 15-ea & 8 (1.8.0_252)
Minecraft 1.16.1
Fabric Loader 0.9.0+build.204

Mods in use:
Clear Skies 1.4.43 from CurseForge (and self-built, but I tested against the CurseForge release as well)
VoxelMap 1.10.7 (unsure if it's all versions or just this one, I tend to only use the latest versions of mods)

Steps to reproduce:
-Install Clear Skies
-Install VoxelMap
-Launch the Game
-Observe the crash

If any further info would help, please let me know.

**Comment by grondag** [comment]
Thank you for the report. It raises the question: why would voxel map need to redirect *that* of all things? It is, unfortunately, a closed source mod so I have no way to inspect that directly. 

I can at least mark it as non-required and perhaps find a different way to patch this. 

(And if I didn’t have so many other projects I’d be tempted to do an open-source map mod. )

**Comment by thedax** [comment]
Thank you for looking into this! Hopefully someday VoxelMap will be made open source, or an alternative will pop up. Map mods seem to have a trend of being closed-source for some reason..
